name: my_nepali_calendar
description: "A feature-rich flutter package for implementing a Nepali calendar system in your applications." 
version: 0.0.5
homepage: https://github.com/crpoudyal/my_nepali_calendar

plugin: 
  platforms:
    android:
    ios:

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:

